[package]
name = "symphonia-xm-ext"
version = "0.1.0"
edition = "2021"

[dependencies]
bitfield-struct = "0.8.0"
either = "1.13.0"
nom = { version = "7.1.3", features = [ "alloc" ] }
symphonia-core = "0.5.4"
